In [1]:
# 引入依赖
import numpy as np
import pandas as pd


In [2]:
# 数据集
# 引入 sklearn 的数据集 iris
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split  # 切分数据集为训练集和测试集
from sklearn.metrics import accuracy_score  # 用来计算分类预测的准确率

In [12]:
# 数据加载  预处理
iris = load_iris()
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

df['class'] = iris.target
df['class'] = df['class'].map({0: iris.target_names[0], 1: iris.target_names[1], 2: iris.target_names[2]})

df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [14]:
x = iris.data
y = iris.target.reshape(-1, 1)
x, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [15]:
# 划分训练集 测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=35, stratify=y)
x_train, x_test, y_train, y_test

(array([[5.4, 3. , 4.5, 1.5],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 2.9, 5.6, 1.8],
        [6.4, 2.8, 5.6, 2.2],
        [4.9, 2.4, 3.3, 1. ],
        [6.3, 3.3, 4.7, 1.6],
        [6.6, 2.9, 4.6, 1.3],
        [5.1, 3.8, 1.6, 0.2],
        [5.4, 3.4, 1.7, 0.2],
        [5.7, 2.5, 5. , 2. ],
        [6.7, 2.5, 5.8, 1.8],
        [5.4, 3.4, 1.5, 0.4],
        [7.4, 2.8, 6.1, 1.9],
        [4.7, 3.2, 1.3, 0.2],
        [5.4, 3.9, 1.3, 0.4],
        [5.8, 2.7, 5.1, 1.9],
        [6.2, 2.9, 4.3, 1.3],
        [7.1, 3. , 5.9, 2.1],
        [5.8, 2.7, 3.9, 1.2],
        [5.2, 2.7, 3.9, 1.4],
        [6.9, 3.2, 5.7, 2.3],
        [5.1, 3.4, 1.5, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [5. , 3.6, 1.4, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [7.7, 3.8, 6.7, 2.2],
        [5.5, 2.5, 4. , 1.3],
        [6.1, 2.8, 4. , 1.3],
        [7.2, 3. , 5.8, 1.6],
        [6.3, 2.5, 4.9, 1.5],
        [6.5, 3. , 5.8, 2.2],
        [6.3, 2.7, 4.9, 1.8],
        [6.8, 3.2, 5.9, 2.3],
        [6

In [40]:
np.argsort(np.sum(np.abs(x_train - x_test[0]), axis=1))[:1]

y_train[[15]].ravel()

array([2])

In [23]:
# 核心算法实现
# 距离函数定义
def l1_distance(a, b):
    return np.sum(np.abs(a-b), axis=1)
def l2_distance(a, b):
    return np.sqrt(np.sum(a-b, axis=1)**2)


# 分类器
class KNN(object):
    def __init__(self, n_neighbors=1, dist_func=l1_distance):
        self.n_neighbors = n_neighbors
        self.dist_func = dist_func
        
    # 训练方法
    def fit(self, x, y):
        self.x_train = x
        self.y_train = y
        
    # 预测
    def predict(self, x):
        # 初始化预测分类数组
        y_pred = np.zeros((x.shape[0], 1), dtype=self.y_train.dtype)
        
        for i, x_test in enumerate(x):
            # 计算距离
            dists = self.dist_func(self.x_train, x_test)
            
            # 距离排序
            nn_index = np.argsort(dists)
            
            # 统计频率最高的
            nn_y = self.y_train[nn_index[:self.n_neighbors]].ravel()
            
            y_pred[i] = np.argmax(np.bincount(nn_y))
            
        
        return y_pred
        

In [43]:
knn = KNN(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
# np.equal(res, y_test)
accuracy_score(y_test, y_pred)

0.9777777777777777